const TransactionType = Object.freeze({
  BOOKING_ADVANCE: 'BOOKING_ADVANCE',
  BOOKING_REMAINING: 'BOOKING_REMAINING',
  BOOKING_DEPOSIT: 'BOOKING_DEPOSIT',
  BOOKING_EXTENSION: 'BOOKING_EXTENSION',
  REFUND_FULL: 'REFUND_FULL',
  REFUND_PARTIAL: 'REFUND_PARTIAL',
  REFUND_CANCELLATION: 'REFUND_CANCELLATION',
  PAYOUT_RENTER: 'PAYOUT_RENTER',
  COMMISSION: 'COMMISSION',
});

const TransactionStatus = Object.freeze({
  INITIATED: 'INITIATED',
  PROCESSING: 'PROCESSING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
});

const PaymentPurpose = Object.freeze({
  ADVANCE: 'ADVANCE',
  REMAINING: 'REMAINING',
  DEPOSIT: 'DEPOSIT',
  EXTENSION: 'EXTENSION',
  WALK_IN: 'WALK_IN',
});

const BookingState = Object.freeze({
  DRAFT: 'DRAFT',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  CONFIRMED: 'CONFIRMED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
});

const RefundStatus = Object.freeze({
  REQUESTED: 'REQUESTED',
  APPROVED: 'APPROVED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
});

const PayoutStatus = Object.freeze({
  PENDING: 'PENDING',
  SCHEDULED: 'SCHEDULED',
  PROCESSING: 'PROCESSING',
  PAID: 'PAID',
  FAILED: 'FAILED',
});

const AuditAction = Object.freeze({
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_WEBHOOK: 'PAYMENT_WEBHOOK',
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_COMPLETED: 'BOOKING_COMPLETED',
  BOOKING_EXTENDED: 'BOOKING_EXTENDED',
  REFUND_REQUESTED: 'REFUND_REQUESTED',
  REFUND_APPROVED: 'REFUND_APPROVED',
  REFUND_REJECTED: 'REFUND_REJECTED',
  REFUND_PROCESSED: 'REFUND_PROCESSED',
  COUPON_APPLIED: 'COUPON_APPLIED',
  COUPON_RELEASED: 'COUPON_RELEASED',
  FRAUD_DETECTED: 'FRAUD_DETECTED',
  FRAUD_REVIEWED: 'FRAUD_REVIEWED',
  PAYOUT_SCHEDULED: 'PAYOUT_SCHEDULED',
  PAYOUT_COMPLETED: 'PAYOUT_COMPLETED',
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  ADMIN_CONFIG_CHANGED: 'ADMIN_CONFIG_CHANGED',
});

const BookingTransition = Object.freeze({
  [BookingState.DRAFT]: [BookingState.PAYMENT_PENDING],
  [BookingState.PAYMENT_PENDING]: [BookingState.CONFIRMED, BookingState.CANCELLED, BookingState.EXPIRED],
  [BookingState.CONFIRMED]: [BookingState.ACTIVE, BookingState.CANCELLED],
  [BookingState.ACTIVE]: [BookingState.COMPLETED, BookingState.CANCELLED],
  [BookingState.COMPLETED]: [],
  [BookingState.CANCELLED]: [],
  [BookingState.EXPIRED]: [],
});

const RefundTransition = Object.freeze({
  [RefundStatus.REQUESTED]: [RefundStatus.APPROVED, RefundStatus.REJECTED],
  [RefundStatus.APPROVED]: [RefundStatus.PROCESSING, RefundStatus.REJECTED],
  [RefundStatus.PROCESSING]: [RefundStatus.COMPLETED, RefundStatus.FAILED],
  [RefundStatus.COMPLETED]: [],
  [RefundStatus.REJECTED]: [],
});

module.exports = {
  TransactionType,
  TransactionStatus,
  PaymentPurpose,
  BookingState,
  RefundStatus,
  PayoutStatus,
  AuditAction,
  BookingTransition,
  RefundTransition,
};
